import { EquipType } from "../modules/inventory/types";
import { images } from "../utils/images";
export const emptyEquip = {
  id: -1,
  name: "",
  image: "",
  STR: 0,
  DEX: 0,
  INT: 0,
  LUK: 0,
  MaxHP: 0,
  MaxMP: 0,
  WEAPON_ATTACK: 0,
  MAGIC_ATTACK: 0,
  upgrade_avalable: 0,
  max_upgrade: 0,
  upgrade: 0,
  max_star: 0,
  star: 0,
};

export const equips: EquipType[] = [
  {
    id: 0,
    name: "나무 검",
    image: images.wood_weapon,
    STR: 10,
    DEX: 10,
    INT: 5,
    LUK: 5,
    MaxHP: 100,
    MaxMP: 100,
    WEAPON_ATTACK: 100,
    MAGIC_ATTACK: 5,
    upgrade_avalable: 10,
    max_upgrade: 10,
    upgrade: 0,
    max_star: 25,
    star: 0,
  },
  {
    id: 1,
    name: "거품 광선",
    image: images.burble_weapon,
    STR: 5,
    DEX: 5,
    INT: 10,
    LUK: 10,
    MaxHP: 100,
    MaxMP: 100,
    WEAPON_ATTACK: 5,
    MAGIC_ATTACK: 100,
    upgrade_avalable: 10,
    max_upgrade: 10,
    upgrade: 0,
    max_star: 25,
    star: 0,
  },
];
