import { EquipType } from "../modules/inventory/types";
import IMAGE from "../utils/images";
export const emptyEquip = {
  id: -1,
  name: "",
  image: "",
  STR: 0,
  DEX: 0,
  INT: 0,
  LUK: 0,
  MaxHP: 0,
  MaxMP: 0,
  WEAPON_ATTACK: 0,
  MAGIC_ATTACK: 0,
  upgrade_avalable: 0,
  max_upgrade: 0,
  upgrade: 0,
  max_star: 0,
  star: 0,
};

export const equips: EquipType[] = [
  {
    id: 0,
    name: "주황버섯 갓",
    image: IMAGE.EquipImages[0],
    STR: 10,
    DEX: 10,
    INT: 5,
    LUK: 5,
    MaxHP: 100,
    MaxMP: 100,
    WEAPON_ATTACK: 100,
    MAGIC_ATTACK: 5,
    upgrade_avalable: 10,
    max_upgrade: 10,
    upgrade: 0,
    max_star: 25,
    star: 12,
  },
  {
    id: 1,
    name: "빨간 리본",
    image: IMAGE.EquipImages[1],
    STR: 5,
    DEX: 5,
    INT: 10,
    LUK: 10,
    MaxHP: 100,
    MaxMP: 100,
    WEAPON_ATTACK: 5,
    MAGIC_ATTACK: 100,
    upgrade_avalable: 10,
    max_upgrade: 10,
    upgrade: 0,
    max_star: 25,
    star: 17,
  },
  {
    id: 3,
    name: "나무 검",
    image: IMAGE.EquipImages[2],
    STR: 5,
    DEX: 5,
    INT: 10,
    LUK: 10,
    MaxHP: 100,
    MaxMP: 100,
    WEAPON_ATTACK: 5,
    MAGIC_ATTACK: 100,
    upgrade_avalable: 10,
    max_upgrade: 10,
    upgrade: 0,
    max_star: 25,
    star: 22,
  },
  {
    id: 4,
    name: "슬라임 액체",
    image: IMAGE.EquipImages[3],
    STR: 5,
    DEX: 5,
    INT: 10,
    LUK: 10,
    MaxHP: 100,
    MaxMP: 100,
    WEAPON_ATTACK: 5,
    MAGIC_ATTACK: 100,
    upgrade_avalable: 10,
    max_upgrade: 10,
    upgrade: 0,
    max_star: 25,
    star: 5,
  },
  {
    id: 5,
    name: "나뭇잎 선풍",
    image: IMAGE.EquipImages[4],
    STR: 5,
    DEX: 5,
    INT: 10,
    LUK: 10,
    MaxHP: 100,
    MaxMP: 100,
    WEAPON_ATTACK: 5,
    MAGIC_ATTACK: 100,
    upgrade_avalable: 10,
    max_upgrade: 10,
    upgrade: 0,
    max_star: 25,
    star: 0,
  },
];
