// import { EquipType } from "../modules/item/types";
import { EquipType } from "../modules/inventory";
import IMAGE from "../utils/images";

export const emptyEquip: EquipType = {
  id: -1,
  job: "",
  category: "",
  name: "",
  image: "",
  STR: 0,
  DEX: 0,
  INT: 0,
  LUK: 0,
  baseStr: 0,
  baseDex: 0,
  baseInt: 0,
  baseLuk: 0,
  addStr: 0,
  addDex: 0,
  addInt: 0,
  addLuk: 0,
  chuStr: 0,
  chuDex: 0,
  chuInt: 0,
  chuLuk: 0,
  MaxHP: 0,
  baseHP: 0,
  chuHP: 0,
  addHP: 0,
  MaxMP: 0,
  baseMP: 0,
  chuMP: 0,
  addMP: 0,
  WEAPON_ATTACK: 0,
  baseWA: 0,
  chuWA: 0,
  addWA: 0,
  MAGIC_ATTACK: 0,
  baseMA: 0,
  chuMA: 0,
  addMA: 0,
  allStat: 0,
  baseAllStat: 0,
  chuAllStat: 0,
  addAllStat: 0,
  upgrade_avalable: 0,
  max_upgrade: 0,
  upgrade: 0,
  max_star: 0,
  star: 0,
};

export const equips: EquipType[] = [
  {
    id: 0,
    job: "전 직업",
    category: "한손검",
    name: "주황버섯 갓",
    image: IMAGE.EquipImages[0],
    STR: 10,
    DEX: 10,
    INT: 0,
    LUK: 0,
    baseStr: 10,
    baseDex: 10,
    baseInt: 0,
    baseLuk: 0,
    addStr: 0,
    addDex: 0,
    addInt: 5,
    addLuk: 0,
    chuStr: 0,
    chuDex: 0,
    chuInt: 0,
    chuLuk: 2,
    MaxHP: 100,
    baseHP: 100,
    chuHP: 50,
    addHP: 0,
    MaxMP: 100,
    baseMP: 100,
    chuMP: 50,
    addMP: 0,
    WEAPON_ATTACK: 100,
    baseWA: 100,
    chuWA: 50,
    addWA: 50,
    MAGIC_ATTACK: 5,
    baseMA: 10,
    chuMA: 5,
    addMA: 5,
    allStat: 5,
    baseAllStat: 5,
    chuAllStat: 5,
    addAllStat: 5,
    max_upgrade: 10,
    upgrade_avalable: 3,
    upgrade: 3,
    max_star: 25,
    star: 12,
  },
  {
    id: 1,
    name: "빨간 리본",
    job: "전 직업",
    category: "한손검",
    image: IMAGE.EquipImages[1],
    STR: 10,
    DEX: 10,
    INT: 5,
    LUK: 5,
    baseStr: 20,
    baseDex: 20,
    baseInt: 10,
    baseLuk: 10,
    addStr: 10,
    addDex: 0,
    addInt: 0,
    addLuk: 10,
    chuStr: 10,
    chuDex: 5,
    chuInt: 0,
    chuLuk: 0,
    MaxHP: 100,
    baseHP: 100,
    chuHP: 50,
    addHP: 0,
    MaxMP: 100,
    baseMP: 100,
    chuMP: 50,
    addMP: 0,
    WEAPON_ATTACK: 100,
    baseWA: 100,
    chuWA: 50,
    addWA: 50,
    MAGIC_ATTACK: 5,
    baseMA: 10,
    chuMA: 5,
    addMA: 5,
    allStat: 5,
    baseAllStat: 5,
    chuAllStat: 5,
    addAllStat: 5,
    max_upgrade: 8,
    upgrade_avalable: 6,
    upgrade: 2,
    max_star: 25,
    star: 17,
  },
  {
    id: 3,
    name: "나무 검",
    job: "전 직업",
    category: "한손검",
    image: IMAGE.EquipImages[2],
    STR: 10,
    DEX: 10,
    INT: 5,
    LUK: 5,
    baseStr: 30,
    baseDex: 30,
    baseInt: 30,
    baseLuk: 30,
    addStr: 30,
    addDex: 30,
    addInt: 30,
    addLuk: 30,
    chuStr: 5,
    chuDex: 5,
    chuInt: 5,
    chuLuk: 0,
    MaxHP: 100,
    baseHP: 100,
    chuHP: 50,
    addHP: 0,
    MaxMP: 100,
    baseMP: 100,
    chuMP: 50,
    addMP: 0,
    WEAPON_ATTACK: 100,
    baseWA: 100,
    chuWA: 50,
    addWA: 50,
    MAGIC_ATTACK: 5,
    baseMA: 10,
    chuMA: 5,
    addMA: 5,
    allStat: 5,
    baseAllStat: 5,
    chuAllStat: 5,
    addAllStat: 5,
    max_upgrade: 7,
    upgrade_avalable: 4,
    upgrade: 0,
    max_star: 25,
    star: 22,
  },
  {
    id: 4,
    name: "슬라임 액체",
    job: "전 직업",
    category: "한손검",
    image: IMAGE.EquipImages[3],
    STR: 10,
    DEX: 10,
    INT: 5,
    LUK: 5,
    baseStr: 100,
    baseDex: 100,
    baseInt: 50,
    baseLuk: 50,
    addStr: 50,
    addDex: 50,
    addInt: 5,
    addLuk: 5,
    chuStr: 50,
    chuDex: 50,
    chuInt: 50,
    chuLuk: 50,
    MaxHP: 100,
    baseHP: 100,
    chuHP: 50,
    addHP: 0,
    MaxMP: 100,
    baseMP: 100,
    chuMP: 50,
    addMP: 0,
    WEAPON_ATTACK: 100,
    baseWA: 100,
    chuWA: 50,
    addWA: 50,
    MAGIC_ATTACK: 5,
    baseMA: 10,
    chuMA: 5,
    addMA: 5,
    allStat: 5,
    baseAllStat: 5,
    chuAllStat: 5,
    addAllStat: 5,
    upgrade_avalable: 0,
    max_upgrade: 10,
    upgrade: 10,
    max_star: 25,
    star: 5,
  },
  {
    id: 5,
    name: "나뭇잎 선풍",
    job: "전 직업",
    category: "한손검",
    image: IMAGE.EquipImages[4],
    STR: 10,
    DEX: 10,
    INT: 5,
    LUK: 5,
    baseStr: 15,
    baseDex: 15,
    baseInt: 55,
    baseLuk: 55,
    addStr: 5,
    addDex: 5,
    addInt: 55,
    addLuk: 55,
    chuStr: 0,
    chuDex: 0,
    chuInt: 0,
    chuLuk: 55,
    MaxHP: 100,
    baseHP: 100,
    chuHP: 50,
    addHP: 0,
    MaxMP: 100,
    baseMP: 100,
    chuMP: 50,
    addMP: 0,
    WEAPON_ATTACK: 100,
    baseWA: 100,
    chuWA: 50,
    addWA: 50,
    MAGIC_ATTACK: 5,
    baseMA: 10,
    chuMA: 5,
    addMA: 5,
    allStat: 5,
    baseAllStat: 5,
    chuAllStat: 5,
    addAllStat: 5,
    upgrade_avalable: 3,
    max_upgrade: 10,
    upgrade: 5,
    max_star: 25,
    star: 0,
  },
];
